#!/bin/bash

cd $(dirname $0)
docker rm hcc-dotfiles-release-container || true

# Read Dockerfile from stdin because we don't need to overhead of build context
docker build -t hcc-dotfiles-release - < Dockerfile

# docker run -v `pwd`:/home/dotbuilder/src/hcc-dotfiles -v /ldata/src/ros/bar_truck:/home/dotbuilder/src/bar_truck -v /tmp/local:/home/dotbuilder/.local --net host --name hcc-dotfiles-release-container -it hcc-dotfiles-release
docker run --name hcc-dotfiles-release-container \
    -v `pwd`:/home/dotbuilder/src/hcc-dotfiles \
    --net host \
    -it \
    hcc-dotfiles-release
