#!/bin/bash

PS4='+${BASH_SOURCE}: ${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): } '
set -x

scriptdir=$(realpath $(dirname "$0"))

get_ubuntu_version() {
    # Assume "jammy" if unknown due to missing lsb_release package
    # (common in Docker containers and debootstrap chroot's)
    # All we really care about is "xenial" vs "not xenial".
    lsb_release -cs 2>/dev/null || echo 'jammy'
}

mklink() {
    local real_src="$(realpath $1)"

    local real_dest="$2"
    mkdir_verbose $(dirname $real_dest)
    if [[ -h "$real_dest" ]]; then
        local tmp
        if ! tmp="$(readlink -f ${real_dest})"; then
            echo Removing broken symlink at ${real_dest}
            \rm -f "${real_dest}"
        else
            :
            # real_dest="${tmp}"
        fi
    else
        :
        # real_dest="$(realpath --canonicalize-missing $2)"
    fi

    local relative_src=$(python3 -c "import os.path; print(os.path.relpath('${real_src}', '$(realpath $(dirname ${real_dest}))'))")

    if [[ -h "${real_dest}" ]]; then
        local existing_src="$(readlink ${real_dest})"

        if [[ "${existing_src}" == "${relative_src}" ]]; then
            return 0
        elif [[ "${opt_force}" == '0' ]]; then
            echo "Not overwriting existing symlink: ${real_dest} -> ${existing_src}"
            echo "    (Would link this to ${relative_src})"
            return 1
        else
            [[ $opt_verbose == 1 ]] && echo rm -f "${real_dest}"
            rm -f "${real_dest}"
        fi
    elif [[ -e "${real_dest}" ]]; then
        if [[ "${opt_force}" == '0' ]]; then
            echo "Not overwriting existing real file: ${real_dest}"
            echo "    (Would link this to ${relative_src})"
            return 1
        else
            [[ $opt_verbose == 1 ]] && echo rm -f "${real_dest}"
            rm -f "${real_dest}"
        fi
    fi

    [[ $opt_verbose == 1 ]] && echo ln -s "${relative_src}" "${real_dest}"
    ln -s "${relative_src}" "${real_dest}"
}

mkdir_verbose() {
    dir="$1"

    if [[ ! -d  "${dir}" ]]; then
        [[ $opt_verbose == 1 ]] && echo mkdir -p "${dir}"
        mkdir -p "${dir}"
    fi
}

lntree() {
    src_tree="$1"
    dest_tree="$2"

    mkdir_verbose "${dest_tree}"

    pushd "$src_tree" >/dev/null || return 1
    for file in $(find .); do
        file="${file#.}"
        file="${file#/}"
        if [[ -d "${file}" ]]; then
            mkdir_verbose "${dest_tree}/${file}"
        elif [[ -f "${file}" ]]; then
            mklink "${file}" "${dest_tree}/${file}"
        fi
    done
    popd >/dev/null
}

promptyn() {
    local prompt="$1"
    local default="Y"
    local prompt_yn="[Yn]"
    if [[ "${2^^}" == N ]]; then
        default='N'
        prompt_yn="[yN]"
    fi
    local REPLY=unset
    while [[ -n "${REPLY}" && "${REPLY^^}" != [YN] ]]; do
        echo
        read -p "$prompt $prompt_yn "
    done
    [[ -z "$REPLY" ]] && REPLY="$default"
    [[ "${REPLY^^}" == Y ]]  # This expression is the return value
}

opt_verbose=1
opt_force=0
opt_yes=0
opt_debug=0
opt_eatmydata=''
opt_apt=1
opt_locale=1
opt_nodejs=1
opt_nvim=1
opt_nvim_plugins=1
opt_tmux=1
# Transform long options to short ones because getopts builtin is dumb and we don't
# want to rely on external getopt.
for arg in "$@"; do
    shift
    case "$arg" in
        "--force")     set -- "$@" "-f" ;;
        "--yes")       set -- "$@" "-y" ;;
        "--eatmydata") set -- "$@" "-e" ;;
        "--debug")     set -- "$@" "-d" ;;
        "--no-apt")    set -- "$@" "-a" ;;
        "--no-locale") set -- "$@" "-l" ;;
        "--no-nodejs") set -- "$@" "-n" ;;
        "--no-nvim")   set -- "$@" "-m" ;;
        "--no-nvim-plugins")   set -- "$@" "-M" ;;
        "--no-tmux")   set -- "$@" "-t" ;;
        "--minimal")   set -- "$@" "-a" "-a" "-l" "-n" "-m" "-M" "-t" ;;
        "--help")      set -- "$@" "-h" ;;
        *)             set -- "$@" $arg ;;
    esac
done
while getopts "fyedalnmth" opt; do
    case ${opt} in
        f)
            opt_force=1
            ;;
        y)
            opt_yes=1
            ;;
        e)
            eatmydata true || sudo apt install -y eatmydata
            eatmydata true && opt_eatmydata=eatmydata
            ;;
        d)
            opt_debug=1
            PS4='+${BASH_SOURCE}: ${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): } '
            set -x
            ;;
        a)
            opt_apt=0
            ;;
        l)
            opt_locale=0
            ;;
        n)
            opt_nodejs=0
            ;;
        m)
            opt_nvim=0
            ;;
        M)
            opt_nvim_plugins=0
            ;;
        t)
            opt_tmux=0
            ;;
        h|\?)
            echo "Usage: $0 options"
            echo "    -f, --force     Force creation of symlinks, overwriting existing"
            echo "    -y, --yes       Answer Yes to all questions"
            echo "    -e, --eatmydata Run apt installs under eatmydata for speed"
            echo "    -d, --debug     Give debug output (shell set -x)"
            echo "    --no-apt        Do not run any APT commands"
            echo "    --no-locale     Do not set up locales"
            echo "    --no-nodejs     Do not run install Node.js"
            echo "    --no-nvim       Do not run install Nvim"
            echo "    --no-nvim-plugins Do not run install Nvim plugins"
            echo "    --no-tmux       Do not run install tmux plugins"
            echo "    --minimal       Equiv. to  --no-apt --no-locale --no-nodejs --no-nvim --no-tmux"
            echo "    -h, --help      Print this message"
            exit 1
    esac
done
is_yes() {
    [[ "$opt_yes" == "1" ]]
}

required_packages_common=(
    apt-utils
    locales
    git
    curl
    fuse  # Needed by nvim, since it is an AppImage
    python3-dev
    python3-pip
    python3-virtualenv
    python3-venv  # Needed by coc-jedi Neovim plugin
    python3-setuptools
    tmux
    zsh
)

# NOTE: These packages do not exist on focal & later
required_packages_xenial=(
    python-dev
    python-pip
    python-virtualenv
    python-setuptools
)

do_install_packages() {
    apt list -qq "$@"
    echo
    if is_yes || promptyn 'Install any packages in the above list that are missing?' Y; then
        sudo ${opt_eatmydata} apt install -y "$@"
    fi
}

install_packages() {
    sudo ${opt_eatmydata} apt update
    [[ -n ${opt_eatmydata} ]] && sync
    do_install_packages "${required_packages_common[@]}"
    ubuntu_ver=$(get_ubuntu_version)
    [[ $ubuntu_ver == "xenial" ]] && install_packages "${required_packages_xenial[@]}"
    [[ -n ${opt_eatmydata} ]] && sync
}

cd "${scriptdir}"
[[ $opt_apt -eq 1 ]] && install_packages

setup_locale() {
    sudo locale-gen en_US.UTF-8
    sudo update-locale LANG=en_US.UTF-8
}
[[ $opt_locale -eq 1 ]] && setup_locale

git submodule update --init --recursive
mklink config/.zsh                ~/.zsh
mklink config/.zshrc              ~/.zshrc
mklink bin                        ~/bin
mklink config/.gvimrc             ~/.gvimrc
mklink config/.vimrc              ~/.vimrc
mklink config/.vim                ~/.vim
mklink config/.vim                ~/.config/nvim  # Neovim will share .vim config
mklink config/.tmux.conf          ~/.tmux.conf
mklink config/.tmux               ~/.tmux
mklink config/.config/htop/htoprc ~/.config/htop/htoprc
mklink .fonts                     ~/.fonts
mklink config/.terminfo           ~/.terminfo
mklink config/.gitconfig          ~/.gitconfig
echo

# Only needed for xenial
upgrade_pip() {
    # Last version of pip that runs in Python 2.7 and 3.5
    pip install --user --upgrade pip==20.3.4
    pip3 install --user --upgrade pip==20.3.4
    hash -r  # Teach this shell about the new pip
}

inst_nodejs() {
    mkdir -p ~/.local
    local script_name=$(mktemp /tmp/nodejs-install-script.XXXXXX)
    curl -Ls install-node.now.sh/lts >> ${script_name}
    chmod +x ${script_name}
    local yes_arg=''
    is_yes && yes_arg='--yes'
    local prefix=~/.local   # Put in temp variable to cause tilde expansion
    ${script_name} --prefix=${prefix} ${yes_arg}
}

inst_nvim() {
    local neovim_version=stable
    echo Installing Neovim ${neovim_version} AppImage in ~/.local/bin
    mkdir -p ~/.local/bin/
    curl -L -o ~/.local/bin/nvim-${neovim_version}.appimage \
        "https://github.com/neovim/neovim/releases/download/${neovim_version}/nvim.appimage"
    chmod +x ~/.local/bin/nvim-${neovim_version}.appimage
    ln -s nvim-${neovim_version}.appimage ~/.local/bin/nvim
}

inst_virtualenv() {
    mkdir  -p ~/ve
    python3 -m virtualenv --python=python3 ~/ve/py3neovim
    inst_neovim_stuff_in_virtualenv ~/ve/py3neovim
    if [[ $ubuntu_ver == "xenial" ]]; then
        python3 -m virtualenv --python=python2 ~/ve/py2neovim
        inst_neovim_stuff_in_virtualenv ~/ve/py2neovim
    fi
}

inst_neovim_stuff_in_virtualenv() {
    local virtualenv_path="$1"
    # Do this in a subshell so I don't mess with this shell's config:
    (
        source $virtualenv_path/bin/activate
        pip install --upgrade pynvim
    )
}

inst_neovim_remote() {
    # Since this not used by nvim itself but by the user in a shell, put this
    # in ~/.local rather than a Python virtenv
    pip3 install --user wheel
    pip3 install --user neovim-remote
}

zsh_first_run() {
    echo "Running zsh to complete one-time setup. May produce messages that"
    echo "Look like errors, but you can ignore these."
    echo
    touch ~/.z  # Keep .fzf from complaining
    NO_SSH_AGENT=1 zsh -i -c exit
}

# After upgrading pip in ~/.local/bin, we want to use it, so make sure the
# .local dirs are in the path for this script
export PATH=~/bin:~/.local/usr/local/bin:~/.local/usr/bin:~/.local/bin:$PATH

zsh_first_run

if [[ $ubuntu_ver == "xenial" ]]; then
    if is_yes || promptyn "Do you want to upgrade pip (recommended for Ubuntu 16.04 xenial)?" Y; then
        upgrade_pip
    fi
fi

if [[ $opt_tmux == 1 ]] && (is_yes || promptyn "Do you want to install tmux plugins?" Y); then
    # Clear $TMUX in case we're running nested. We want our own instance for plugin install.
    TMUX= ~/.tmux/plugins/tpm/bin/install_plugins
fi

if [[ $opt_nodejs == 1 ]] && (is_yes || promptyn 'Do you want to install node.js in ~/.local (Needed by coc.nvim Neovim plugin)' Y); then
    inst_nodejs
fi

if [[ $opt_nvim == 1 ]] && (is_yes || promptyn 'Do you want to install Neovim AppImage?' Y); then
    inst_nvim
    inst_virtualenv
    inst_neovim_remote
    echo
    if [[ $opt_nvim_plugins == 1 ]] && (is_yes || promptyn 'Will now launch Neovim in headless mode to install plugins. Proceed?' Y); then
        nvim --headless -c InstallAllPluginsSync -c qa
        # nvim typically exits with status 1 even though it succeeded.
        # Prevent whole script from exiting with failure status:
        true
    fi
fi
