#!/bin/bash

scriptdir=$(realpath $(dirname "$0"))

mklink() {
    local real_src="$(realpath $1)"

    local real_dest="$2"
    mkdir_verbose $(dirname $real_dest)
    if [[ -h "$real_dest" ]]; then
        local tmp
        if ! tmp="$(readlink -f ${real_dest})"; then
            echo Removing broken symlink at ${real_dest}
            \rm -f "${real_dest}"
        else
            :
            # real_dest="${tmp}"
        fi
    else
        :
        # real_dest="$(realpath --canonicalize-missing $2)"
    fi

    local relative_src=$(python -c "import os.path; print os.path.relpath('${real_src}', '$(realpath $(dirname ${real_dest}))')")

    if [[ -h "${real_dest}" ]]; then
        local existing_src="$(readlink ${real_dest})"

        if [[ "${existing_src}" == "${relative_src}" ]]; then
            return 0
        elif [[ "${opt_force}" == '0' ]]; then
            echo "Not overwriting existing symlink: ${real_dest} -> ${existing_src}"
            echo "    (Would link this to ${relative_src})"
            return 1
        else
            [[ $opt_verbose == 1 ]] && echo rm -f "${real_dest}"
            rm -f "${real_dest}"
        fi
    elif [[ -e "${real_dest}" ]]; then
        if [[ "${opt_force}" == '0' ]]; then
            echo "Not overwriting existing real file: ${real_dest}"
            echo "    (Would link this to ${relative_src})"
            return 1
        else
            [[ $opt_verbose == 1 ]] && echo rm -f "${real_dest}"
            rm -f "${real_dest}"
        fi
    fi

    [[ $opt_verbose == 1 ]] && echo ln -s "${relative_src}" "${real_dest}"
    ln -s "${relative_src}" "${real_dest}"
}

mkdir_verbose() {
    dir="$1"

    if [[ ! -d  "${dir}" ]]; then
        [[ $opt_verbose == 1 ]] && echo mkdir -p "${dir}"
        mkdir -p "${dir}"
    fi
}

lntree() {
    src_tree="$1"
    dest_tree="$2"

    mkdir_verbose "${dest_tree}"

    pushd "$src_tree" >/dev/null || return 1
    for file in $(find .); do
        file="${file#.}"
        file="${file#/}"
        if [[ -d "${file}" ]]; then
            mkdir_verbose "${dest_tree}/${file}"
        elif [[ -f "${file}" ]]; then
            mklink "${file}" "${dest_tree}/${file}"
        fi
    done
    popd >/dev/null
}

promptyn() {
    local prompt="$1"
    local default="Y"
    local prompt_yn="[Yn]"
    if [[ "${2^^}" == N ]]; then
        default='N'
        prompt_yn="[yN]"
    fi
    local REPLY=unset
    while [[ -n "${REPLY}" && "${REPLY^^}" != [YN] ]]; do
        echo
        read -p "$prompt $prompt_yn "
    done
    [[ -z "$REPLY" ]] && REPLY="$default"
    [[ "${REPLY^^}" == Y ]]  # This expression is the return value
}

opt_verbose=1
opt_force=0
opt_yes=0
while getopts ":fy" opt; do
    case ${opt} in
        f)
            opt_force=1
            ;;
        y)
            opt_yes=1
            ;;
        \?)
            echo "Usage: $0 [-f] [-y]"
            echo "    -f  Force creation of symlinks, overwriting existing"
            echo "    -y  Answer Yes to all questions"
            exit 1
    esac
done
is_yes() {
    [[ "$opt_yes" == "1" ]]
}

required_packages=(
    git
    curl
    apt-utils
    python-dev
    python3-dev
    python-pip
    python3-pip
    python3-virtualenv
    python-virtualenv
    python-setuptools
    python3-setuptools
    build-essential     # cquery nvim plugin
    cmake               # cquery nvim plugin
)

install_packages() {
    apt list -qq "$@"
    echo
    if is_yes || promptyn 'Install any packages in the above list that are missing?' Y; then
        sudo apt install -y "$@"
    fi
}

cd "${scriptdir}"
pwd

install_packages "${required_packages[@]}"

git submodule update --init --recursive
mklink config/.zsh                ~/.zsh
mklink config/.zshrc              ~/.zshrc
mklink bin                        ~/bin
mklink config/.gvimrc             ~/.gvimrc
mklink config/.vimrc              ~/.vimrc
mklink config/.vim                ~/.vim
mklink config/.vim                ~/.config/nvim  # Neovim will share .vim config
mklink config/.tmux.conf          ~/.tmux.conf
mklink config/.tmux               ~/.tmux
mklink config/.config/htop/htoprc ~/.config/htop/htoprc
mklink .fonts                     ~/.fonts
mklink config/.terminfo           ~/.terminfo
mklink config/.gitconfig          ~/.gitconfig
echo

upgrade_pip() {
    pip install --upgrade pip
    pip3 install --upgrade pip
    hash -r  # Teach this shell about the new pip
}

inst_nodejs() {
    local script_name=$(mktemp /tmp/nodejs-install-script.XXXXXX)
    curl -Ls install-node.now.sh/lts >> ${script_name}
    chmod +x ${script_name}
    local yes_arg=''
    is_yes && yes_arg='--yes'
    local prefix=~/.local   # Put in temp variable to cause tilde expansion
    ${script_name} --prefix=${prefix} ${yes_arg}
}

inst_nvim() {
    local neovim_version=v0.4.3
    echo Installing Neovim ${neovim_version} AppImage in ~/.local/bin
    mkdir -p ~/.local/bin/
    curl -L -o ~/.local/bin/nvim-${neovim_version}.appimage \
        "https://github.com/neovim/neovim/releases/download/${neovim_version}/nvim.appimage"
    chmod +x ~/.local/bin/nvim-${neovim_version}.appimage
    ln -s nvim-${neovim_version}.appimage ~/.local/bin/nvim
}

inst_virtualenv() {
    mkdir  -p ~/ve
    python3 -m virtualenv --python=python2 ~/ve/py2neovim
    python3 -m virtualenv --python=python3 ~/ve/py3neovim
    inst_neovim_stuff_in_virtualenv ~/ve/py2neovim
    inst_neovim_stuff_in_virtualenv ~/ve/py3neovim
}

inst_neovim_stuff_in_virtualenv() {
    local virtualenv_path="$1"
    # Do this in a subshell so I don't mess with this shell's config:
    (
        source $virtualenv_path/bin/activate
        pip install --upgrade pynvim
    )
}

inst_neovim_remote() {
    # Since this not used by nvim itself but by the user in a shell, put this
    # in ~/.local rather than a Python virtenv
    pip3 install --user wheel
    pip3 install --user neovim-remote
}

# After upgrading pip in ~/.local/bin, we want to use it, so make sure the
# .local dirs are in the path for this script
export PATH=~/bin:~/.local/usr/local/bin:~/.local/usr/bin:~/.local/bin:$PATH

if is_yes || promptyn "Do you want to upgrade pip (recommended for Ubuntu 16.04)?" Y; then
    upgrade_pip
fi

if is_yes || promptyn "Do you want to install tmux plugins?" Y; then
    ~/.tmux/plugins/tpm/bin/install_plugins
fi

if is_yes || promptyn 'Do you want to install node.js in ~/.local (Needed by coc.nvim Neovim plugin)' Y; then
    inst_nodejs
fi

if is_yes || promptyn 'Do you want to install & configure Neovim AppImage?' Y; then
    inst_nvim
    inst_virtualenv
    inst_neovim_remote
    echo
    if is_yes || promptyn 'Will now launch Neovim to install plugins. Manually exit it when finished. Proceed?' Y; then
        nvim
    fi
fi
