#!/bin/bash
# Install the language servers used by my NeoVim config

sudo apt install clangd-11
npm install -g bash-language-server
npm install -g dockerfile-language-server-nodejs
pip install -U cmake-language-server
npm install -g dot-language-server
npm install -g pyright
pip install -U jedi-language-server
npm install -g vscode-langservers-extracted   # html, cssls
npm install -g yaml-language-server
